-- Data for empresa_contratante
INSERT INTO public.empresa_contratante ("contrato_id", "natureza", "nome", "area", "departamento", "cnpj", "email", "telefone", "gestor_responsavel", "unidade_administrativa", "created_at", "updated_at") VALUES ('CTR-2026-SYS', 'Privada', 'Sagacitas Sistemas', 'Tecnologia Aplicada a Administração e Finanças', 'Engenharia', NULL, NULL, NULL, NULL, NULL, '2026-08-16T18:01:00.565546+00:00', '2026-08-16T18:01:00.565546+00:00') ON CONFLICT DO NOTHING;

-- Data for empresas_fornecedores
INSERT INTO public.empresas_fornecedores ("id", "contrato_id", "nome", "cnpj_cpf", "tipo", "email_contato", "telefone", "status", "total_faturado", "created_at") VALUES ('FORN-001', 'CTR-2026-SYS', 'Construtora Alpha Ltda', '55.675.888/0001-54', 'FORNECEDOR', '', '', 'ATIVO', 0, '2026-08-17') ON CONFLICT DO NOTHING;
INSERT INTO public.empresas_fornecedores ("id", "contrato_id", "nome", "cnpj_cpf", "tipo", "email_contato", "telefone", "status", "total_faturado", "created_at") VALUES ('FORN-002', 'CTR-2026-SYS', 'Beta Instalações SA', '78.709.153/0001-08', 'FORNECEDOR', '', '', 'ATIVO', 0, '2026-08-17') ON CONFLICT DO NOTHING;
INSERT INTO public.empresas_fornecedores ("id", "contrato_id", "nome", "cnpj_cpf", "tipo", "email_contato", "telefone", "status", "total_faturado", "created_at") VALUES ('FORN-003', 'CTR-2026-SYS', 'Gama Engenharia', '57.006.138/0001-15', 'FORNECEDOR', '', '', 'BLOQUEADO', 0, '2026-08-17') ON CONFLICT DO NOTHING;
INSERT INTO public.empresas_fornecedores ("id", "contrato_id", "nome", "cnpj_cpf", "tipo", "email_contato", "telefone", "status", "total_faturado", "created_at") VALUES ('GER-2026-SYS', 'CTR-2026-SYS', 'Sagacitas Sistemas ltds.', '21047056000171', 'CONTRATANTE', '', '27996629143', 'ATIVO', 0, '2026-08-17') ON CONFLICT DO NOTHING;

-- Data for permissoes_usuario
INSERT INTO public.permissoes_usuario ("id", "usuario_uid", "contrato_id", "empresa_id", "empresas_criar", "empresas_ler", "empresas_editar", "empresas_excluir", "projetos_criar", "projetos_ler", "projetos_editar", "projetos_excluir", "medicoes_criar", "medicoes_ler", "medicoes_editar", "medicoes_excluir", "financeiro_criar", "financeiro_ler", "financeiro_editar", "financeiro_excluir", "relatorios_ler", "usuarios_criar", "usuarios_ler", "usuarios_editar", "usuarios_excluir", "created_at", "updated_at", "cronogramas_criar", "cronogramas_ler", "cronogramas_editar", "cronogramas_excluir", "rdo_criar", "rdo_ler", "rdo_editar", "rdo_excluir", "os_criar", "os_ler", "os_editar", "os_excluir", "contratos_criar", "contratos_ler", "contratos_editar", "contratos_excluir", "entidades_criar", "entidades_ler", "entidades_editar", "entidades_excluir", "configuracoes_criar", "configuracoes_ler", "configuracoes_editar", "configuracoes_excluir") VALUES ('f2f8ddca-ef7d-496a-bd5f-433950fd4d80', 'uid-visitante-mock', 'CTR-2026-SYS', NULL, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, '2026-08-17T22:41:37.698296+00:00', '2026-08-17T22:41:37.685+00:00', false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false) ON CONFLICT DO NOTHING;
INSERT INTO public.permissoes_usuario ("id", "usuario_uid", "contrato_id", "empresa_id", "empresas_criar", "empresas_ler", "empresas_editar", "empresas_excluir", "projetos_criar", "projetos_ler", "projetos_editar", "projetos_excluir", "medicoes_criar", "medicoes_ler", "medicoes_editar", "medicoes_excluir", "financeiro_criar", "financeiro_ler", "financeiro_editar", "financeiro_excluir", "relatorios_ler", "usuarios_criar", "usuarios_ler", "usuarios_editar", "usuarios_excluir", "created_at", "updated_at", "cronogramas_criar", "cronogramas_ler", "cronogramas_editar", "cronogramas_excluir", "rdo_criar", "rdo_ler", "rdo_editar", "rdo_excluir", "os_criar", "os_ler", "os_editar", "os_excluir", "contratos_criar", "contratos_ler", "contratos_editar", "contratos_excluir", "entidades_criar", "entidades_ler", "entidades_editar", "entidades_excluir", "configuracoes_criar", "configuracoes_ler", "configuracoes_editar", "configuracoes_excluir") VALUES ('3dfd19e8-5d77-4be3-9a91-b98f1c798de7', '3G1JNHecTNNTimjaxkUxxTfb9qY2', 'CTR-2026-SYS', NULL, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, '2026-08-18T00:23:34.456071+00:00', '2026-08-18T00:23:34.456071+00:00', true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true) ON CONFLICT DO NOTHING;

