-- Modifica a tabela projetos existente para atuar como a tabela 'obras' do prompt
ALTER TABLE projetos 
  ADD COLUMN IF NOT EXISTS area_construida_m2 NUMERIC(10,2),
  ADD COLUMN IF NOT EXISTS custo_direto_total NUMERIC(15,2),
  ADD COLUMN IF NOT EXISTS jornada_diaria_horas NUMERIC(4,2) DEFAULT 8.0,
  ADD COLUMN IF NOT EXISTS padrao_acabamento VARCHAR(50) DEFAULT 'NORMAL';

-- Cria tabela de Etapas do Orçamento
CREATE TABLE IF NOT EXISTS etapas_orcamento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    projeto_id UUID NOT NULL REFERENCES projetos(id) ON DELETE CASCADE,
    codigo_etapa VARCHAR(50) NOT NULL,
    nome_etapa VARCHAR(255) NOT NULL,
    peso_percentual NUMERIC(5,2),
    valor_total_etapa NUMERIC(15,2),
    pct_mao_de_obra NUMERIC(5,2),
    pct_materiais NUMERIC(5,2),
    pct_equipamentos NUMERIC(5,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Habilita RLS
ALTER TABLE etapas_orcamento ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso as etapas do orçamento" 
ON etapas_orcamento FOR ALL USING (
    EXISTS (SELECT 1 FROM projetos WHERE projetos.id = etapas_orcamento.projeto_id)
);

-- Cria tabela de Parâmetros de Execução (Produtividade / Prazos)
CREATE TABLE IF NOT EXISTS parametros_execucao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etapa_orcamento_id BIGINT NOT NULL REFERENCES etapas_orcamento(id) ON DELETE CASCADE,
    hh_unitario NUMERIC(8,4),
    unidade_medida VARCHAR(50),
    quantidade_total NUMERIC(12,2),
    tamanho_equipe_padrao INTEGER,
    duracao_calculada_dias INTEGER,
    data_inicio_estimada DATE,
    data_fim_estimada DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Habilita RLS
ALTER TABLE parametros_execucao ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso aos parametros de execucao" 
ON parametros_execucao FOR ALL USING (
    EXISTS (SELECT 1 FROM etapas_orcamento WHERE etapas_orcamento.id = parametros_execucao.etapa_orcamento_id)
);

-- Cria tabela de Precedências (Ligações para Gantt / CPM)
CREATE TABLE IF NOT EXISTS precedencias_etapa (
    etapa_id BIGINT NOT NULL REFERENCES etapas_orcamento(id) ON DELETE CASCADE,
    etapa_predecessora_id BIGINT NOT NULL REFERENCES etapas_orcamento(id) ON DELETE CASCADE,
    tipo_relacao VARCHAR(10) DEFAULT 'FS', -- FS, SS, FF, SF
    lag_dias INTEGER DEFAULT 0,
    PRIMARY KEY (etapa_id, etapa_predecessora_id)
);

-- Habilita RLS
ALTER TABLE precedencias_etapa ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso as precedencias" 
ON precedencias_etapa FOR ALL USING (
    EXISTS (SELECT 1 FROM etapas_orcamento WHERE etapas_orcamento.id = precedencias_etapa.etapa_id)
);

-- Cria tabela de Cronograma Físico-Financeiro (Curva S)
CREATE TABLE IF NOT EXISTS cronograma_fisico_financeiro_mensal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    etapa_orcamento_id BIGINT NOT NULL REFERENCES etapas_orcamento(id) ON DELETE CASCADE,
    mes_ano DATE NOT NULL,
    percentual_fisico_previsto NUMERIC(5,2),
    valor_financeiro_previsto NUMERIC(15,2),
    percentual_fisico_realizado NUMERIC(5,2),
    valor_financeiro_realizado NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Habilita RLS
ALTER TABLE cronograma_fisico_financeiro_mensal ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Acesso ao cronograma fisico financeiro" 
ON cronograma_fisico_financeiro_mensal FOR ALL USING (
    EXISTS (SELECT 1 FROM etapas_orcamento WHERE etapas_orcamento.id = cronograma_fisico_financeiro_mensal.etapa_orcamento_id)
);
